server:
  port: 8094
  
spring:
  application:
    name: Eureka_server2
  
eureka:
  instance: 
      hostname: eureka2
  client: 
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8093/eureka/,http://localhost:8095/eureka/
    