server:
  port: 8095
  
spring:
  application:
    name: Eureka_server3
  
eureka:
  instance: 
      hostname: eureka3
  client: 
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8093/eureka/,http://localhost:8094/eureka/
    