#端口号配置
server:
  port: 8092

spring:
  application:
    name: msc_client
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8093/eureka/,http://eureka2:8094/eureka/,http://eureka3:8095/eureka/

   
