server:
  port: 8093
  
spring:
  application:
    name: Eureka_server1
  
eureka:
  instance:
    hostname: eureka1
  client: 
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8094/eureka/,http://localhost:8095/eureka/
    