spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/msc_test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: msc_server

#端口号配置
server:
  port: 8091

mybatis:
  type-aliases-package: top.dycstudy.pojo
#sql 信息打印到控制台输出
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8093/eureka/,http://eureka2:8094/eureka/,http://eureka3:8095/eureka/
